In [138]:
!pip install -U finance-datareader
import pandas as pd
import FinanceDataReader as fdr

Requirement already satisfied: finance-datareader in /usr/local/lib/python3.7/dist-packages (0.9.33)
Requirement already satisfied: requests>=2.3.0 in /usr/local/lib/python3.7/dist-packages (from finance-datareader) (2.23.0)
Requirement already satisfied: lxml in /usr/local/lib/python3.7/dist-packages (from finance-datareader) (4.2.6)
Requirement already satisfied: pandas>=0.19.2 in /usr/local/lib/python3.7/dist-packages (from finance-datareader) (1.3.5)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from finance-datareader) (4.64.0)
Requirement already satisfied: requests-file in /usr/local/lib/python3.7/dist-packages (from finance-datareader) (1.5.1)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.19.2->finance-datareader) (1.21.6)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.19.2->finance-datareader) (2022.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.19.2->finance-datareader) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.19.2->finance-datareader) (1.15.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.3.0->finance-datareader) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.3.0->finance-datareader) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.3.0->finance-datareader) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.3.0->finance-datareader) (2021.10.8)

In [139]:
from numpy import NaN
stocks = fdr.StockListing('KOSPI')
stocks

,Symbol,Market,Name,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
1,095570,KOSPI,AJ네트웍스,산업용 기계 및 장비 임대업,"렌탈(파렛트, OA장비, 건설장비)",2015-08-21,12월,"박대현, 손삼달",http://www.ajnet.co.kr,서울특별시
2,006840,KOSPI,AK홀딩스,기타 금융업,지주사업,1999-08-11,12월,"채형석, 이석주(각자 대표이사)",http://www.aekyunggroup.co.kr,서울특별시
6,152100,KOSPI,ARIRANG 200,NaN,NaN,NaT,NaN,NaN,NaN,NaN
7,295820,KOSPI,ARIRANG 200동일가중,NaN,NaN,NaT,NaN,NaN,NaN,NaN
8,253150,KOSPI,ARIRANG 200선물레버리지,NaN,NaN,NaT,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
7582,000540,KOSPI,흥국화재,보험업,손해보험,1974-12-05,12월,임규준,http://www.insurance.co.kr,서울특별시
7583,000547,KOSPI,흥국화재2우B,NaN,NaN,NaT,NaN,NaN,NaN,NaN
7584,000545,KOSPI,흥국화재우,NaN,NaN,NaT,NaN,NaN,NaN,NaN
7585,003280,KOSPI,흥아해운,해상 운송업,외항화물운송업(케미컬탱커),1976-06-29,12월,이환구,http://www.heung-a.com,서울특별시
7587,419890,KOSPI,히어로즈 단기채권ESG액티브,NaN,NaN,NaT,NaN,NaN,NaN,NaN

In [140]:
stocks.dropna(axis=0, inplace = True)
stocks

,Symbol,Market,Name,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
1,095570,KOSPI,AJ네트웍스,산업용 기계 및 장비 임대업,"렌탈(파렛트, OA장비, 건설장비)",2015-08-21,12월,"박대현, 손삼달",http://www.ajnet.co.kr,서울특별시
2,006840,KOSPI,AK홀딩스,기타 금융업,지주사업,1999-08-11,12월,"채형석, 이석주(각자 대표이사)",http://www.aekyunggroup.co.kr,서울특별시
52,027410,KOSPI,BGF,기타 금융업,지주회사,2014-05-19,12월,홍정국,http://www.bgf.co.kr,서울특별시
53,282330,KOSPI,BGF리테일,종합 소매업,체인화 편의점,2017-12-08,12월,이건준,http://www.bgfretail.com,서울특별시
55,138930,KOSPI,BNK금융지주,기타 금융업,금융지주회사,2011-03-30,12월,김지완,http://www.bnkfg.com,부산광역시
...,...,...,...,...,...,...,...,...,...,...
7562,005870,KOSPI,휴니드,통신 및 방송 장비 제조업,"무선통신기기,군납용무전기,위성방송수신기 제조",1991-09-03,12월,신종석,http://www.huneed.com,인천광역시
7571,079980,KOSPI,휴비스,화학섬유 제조업,"합성섬유(폴리에스테르원사,원면),재생섬유,폴리에스텔 원사,원면,고상칩 제조,도소매",2012-02-23,12월,신유동,http://www.huvis.com,서울특별시
7574,005010,KOSPI,휴스틸,1차 철강 제조업,"강관(배관용,구조용,유정용) 제조,도매",1973-06-29,12월,박훈,http://www.husteel.com,서울특별시
7582,000540,KOSPI,흥국화재,보험업,손해보험,1974-12-05,12월,임규준,http://www.insurance.co.kr,서울특별시
7585,003280,KOSPI,흥아해운,해상 운송업,외항화물운송업(케미컬탱커),1976-06-29,12월,이환구,http://www.heung-a.com,서울특별시

In [141]:
s = stocks['Symbol'].head(100)

In [142]:
df = []
index = []
for i in s:
  try:
    close = fdr.DataReader(i,'2021-05-13','2022-05-13')['Close']
  except:
    continue
  df.append(close)
  index.append(i)

In [143]:
d = pd.concat(df,axis=1)
d.columns = index

In [144]:
d = d.pct_change()

In [145]:
d = d.shift(-1)

In [146]:
d

,095570,006840,027410,282330,138930,001460,001040,079160,000120,011150,...,005490,010950,034120,005090,001380,004060,001770,002360,009160,025530
Date,,,,,,,,,,,,,,,,,,,,,
2021-05-13,0.022876,-0.002976,-0.002878,-0.013889,-0.007353,0.012987,-0.018265,0.009107,-0.008746,-0.009564,...,-0.009126,0.006283,0.197952,0.012687,0.020507,0.012048,0.022013,-0.004255,0.069042,0.015134
2021-05-14,-0.012780,0.041791,-0.002886,0.016901,-0.006173,-0.016667,0.004651,0.045126,-0.002941,-0.021459,...,-0.034211,0.015609,0.108262,0.007973,-0.066194,-0.019841,0.021538,0.042735,-0.050000,-0.020642
2021-05-17,0.001618,-0.008596,-0.004342,0.008310,0.003727,0.002608,0.013889,0.003454,0.011799,0.005482,...,0.050409,0.023566,0.000000,0.005650,0.012658,0.029690,-0.028614,-0.012295,-0.019737,0.028103
2021-05-18,-0.059774,0.011561,-0.008721,-0.021978,-0.014851,0.000000,-0.004566,0.056799,-0.008746,0.001091,...,-0.053178,-0.033033,0.051414,-0.007865,0.000000,-0.005242,0.017054,-0.029046,-0.061521,0.037585
2021-05-20,-0.003436,-0.041429,0.010264,-0.022472,-0.030151,0.002601,-0.041284,-0.026059,-0.002941,-0.019608,...,-0.013699,-0.026915,-0.007335,-0.007928,0.038750,-0.014493,-0.015244,0.004274,-0.002384,-0.029638
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-05-09,-0.014218,-0.016990,-0.030631,0.002674,-0.012706,-0.001124,0.004779,-0.011173,0.025316,-0.005109,...,-0.017794,-0.040359,0.001030,-0.002051,-0.005556,-0.005780,-0.057756,-0.011538,-0.014723,0.000000
2022-05-10,0.000000,0.014815,0.001859,0.024000,-0.029601,-0.005624,0.004756,-0.016949,0.045267,-0.002567,...,-0.005435,-0.009346,-0.008230,-0.007194,0.002793,0.018895,-0.001751,0.019455,-0.022989,-0.002710
2022-05-11,0.012821,-0.053528,-0.040816,0.015625,-0.001326,-0.018100,-0.015385,-0.047893,0.015748,-0.039897,...,-0.005464,0.028302,-0.002075,-0.015528,-0.033426,-0.027104,0.017544,-0.080153,-0.038824,0.000000
2022-05-12,0.069620,0.020566,0.001934,0.007692,0.019920,0.013825,0.010817,0.046278,0.015504,0.004021,...,0.027473,0.013761,0.074844,0.023134,0.014409,0.008798,0.020690,-0.029046,0.002448,0.005435
2022-05-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [147]:
k = (1+d).cumprod() - 1

In [148]:
k = k.drop(['2022-05-13'])

In [149]:
k

,095570,006840,027410,282330,138930,001460,001040,079160,000120,011150,...,005490,010950,034120,005090,001380,004060,001770,002360,009160,025530
Date,,,,,,,,,,,,,,,,,,,,,
2021-05-13,0.022876,-0.002976,-0.002878,-0.013889,-0.007353,0.012987,-0.018265,0.009107,-0.008746,-0.009564,...,-0.009126,0.006283,0.197952,0.012687,0.020507,0.012048,0.022013,-4.255319e-03,0.069042,0.015134
2021-05-14,0.009804,0.038690,-0.005755,0.002778,-0.013480,-0.003896,-0.013699,0.054645,-0.011662,-0.030818,...,-0.043025,0.021990,0.327645,0.020761,-0.047045,-0.008032,0.044025,3.829787e-02,0.015590,-0.005821
2021-05-17,0.011438,0.029762,-0.010072,0.011111,-0.009804,-0.001299,0.000000,0.058288,0.000000,-0.025505,...,0.005215,0.046073,0.327645,0.026528,-0.034982,0.021419,0.014151,2.553191e-02,-0.004454,0.022119
2021-05-18,-0.049020,0.041667,-0.018705,-0.011111,-0.024510,-0.001299,-0.004566,0.118397,-0.008746,-0.024442,...,-0.048240,0.011518,0.395904,0.018454,-0.034982,0.016064,0.031447,-4.255319e-03,-0.065702,0.060536
2021-05-20,-0.052288,-0.001488,-0.008633,-0.033333,-0.053922,0.001299,-0.045662,0.089253,-0.011662,-0.043571,...,-0.061278,-0.015707,0.385666,0.010381,0.002413,0.001339,0.015723,2.220446e-16,-0.067929,0.029104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-05-06,0.034314,-0.386905,-0.201439,0.038889,-0.035539,0.155844,-0.235616,-0.021858,-0.309038,-0.167906,...,-0.267275,0.167539,0.656997,0.124567,-0.565742,-0.073628,-0.047170,1.063830e-01,0.966592,-0.140861
2022-05-09,0.019608,-0.397321,-0.225899,0.041667,-0.047794,0.154545,-0.231963,-0.032787,-0.291545,-0.172157,...,-0.280313,0.120419,0.658703,0.122261,-0.568154,-0.078983,-0.102201,9.361702e-02,0.937639,-0.140861
2022-05-10,0.019608,-0.388393,-0.224460,0.066667,-0.075980,0.148052,-0.228311,-0.049180,-0.259475,-0.174283,...,-0.284224,0.109948,0.645051,0.114187,-0.566948,-0.061580,-0.103774,1.148936e-01,0.893096,-0.143190
2022-05-11,0.032680,-0.421131,-0.256115,0.083333,-0.077206,0.127273,-0.240183,-0.094718,-0.247813,-0.207226,...,-0.288136,0.141361,0.641638,0.096886,-0.581423,-0.087015,-0.088050,2.553191e-02,0.819599,-0.143190
2022-05-12,0.104575,-0.409226,-0.254676,0.091667,-0.058824,0.142857,-0.231963,-0.052823,-0.236152,-0.204038,...,-0.268579,0.157068,0.764505,0.122261,-0.575392,-0.078983,-0.069182,-4.255319e-03,0.824053,-0.138533

In [150]:
momentum = k.loc['2022-05-12']

In [151]:
df_m = pd.DataFrame({'momentum':momentum, 'sector':momentum})
df_m.index = k.columns

In [152]:
df = fdr.StockListing('KOSPI')

In [153]:
for i in df_m.index:
  s = df[df['Symbol'] == i]['Sector']
  if s.iloc[0] == NaN:
    df.drop(i,inplace = True)
    continue
  df_m['sector'][i] = s.iloc[0]

In [154]:
df_m

        momentum            sector
095570  0.104575   산업용 기계 및 장비 임대업
006840 -0.409226            기타 금융업
027410 -0.254676            기타 금융업
282330  0.091667            종합 소매업
138930 -0.058824            기타 금융업
...          ...               ...
004060 -0.078983         상품 종합 도매업
001770 -0.069182         1차 철강 제조업
002360 -0.004255       기초 화학물질 제조업
009160  0.824053         1차 철강 제조업
025530 -0.138533  자동차 부품 및 내장품 판매업

[100 rows x 2 columns]

In [155]:
top = df_m.sort_values('momentum',ascending=False).head(50)
top

            momentum                             sector
004250  1.224215e+00                         플라스틱제품 제조업
079550  1.010349e+00                       무기 및 총포탄 제조업
009160  8.240535e-01                          1차 철강 제조업
011070  7.704485e-01                           전자부품 제조업
034120  7.645051e-01                           텔레비전 방송업
092220  5.550122e-01                            반도체 제조업
383220  5.272727e-01                           봉제의복 제조업
001530  4.048567e-01                             상품 중개업
001250  3.558719e-01                          상품 종합 도매업
001390  3.225256e-01                        기초 화학물질 제조업
005830  2.500000e-01                                보험업
000990  2.048611e-01                            반도체 제조업
030200  1.901743e-01                             전기 통신업
000680  1.876076e-01                          상품 종합 도매업
037560  1.591356e-01                           텔레비전 방송업
010950  1.570681e-01                         석유 정제품 제조업
001460  1.428571e-01                           봉제의복 제조업
005090  1.222607e-01                                전기업
095570  1.045752e-01                    산업용 기계 및 장비 임대업
001120  9.393064e-02                             상품 중개업
282330  9.166667e-02                             종합 소매업
338100  9.010989e-02                       부동산 임대 및 공급업
175330  8.998733e-02                             기타 금융업
012030  6.153846e-02            컴퓨터 프로그래밍, 시스템 통합 및 관리업
023150  3.431373e-02                          알코올음료 제조업
365550  3.313253e-02                       부동산 임대 및 공급업
009440  2.338530e-02                             기타 금융업
033780  1.707317e-02                             담배 제조업
017940  1.540041e-02                          기타 전문 도매업
002380  1.341282e-02                        기타 화학제품 제조업
093050  2.597403e-03                           봉제의복 제조업
400760 -7.771561e-16                       부동산 임대 및 공급업
002360 -4.255319e-03                        기초 화학물질 제조업
105560 -8.503401e-03                             기타 금융업
082740 -2.364532e-02                      일반 목적용 기계 제조업
178920 -2.717391e-02                         플라스틱제품 제조업
079160 -5.282332e-02          영화, 비디오물, 방송프로그램 제작 및 배급업
138930 -5.882353e-02                             기타 금융업
097230 -6.553398e-02                             토목 건설업
344820 -6.560000e-02                      유리 및 유리제품 제조업
001770 -6.918239e-02                          1차 철강 제조업
032640 -7.744108e-02                             전기 통신업
004060 -7.898260e-02                          상품 종합 도매업
006360 -8.630610e-02                             건물 건설업
139130 -8.742004e-02                             기타 금융업
069730 -8.895706e-02                          1차 철강 제조업
008260 -9.219858e-02                          1차 철강 제조업
001060 -9.252282e-02                            의약품 제조업
010120 -1.016334e-01  전동기, 발전기 및 전기 변환 · 공급 · 제어 장치 제조업
010060 -1.034483e-01                        기초 화학물질 제조업

In [156]:
top_group_sector = top.groupby('sector')
top_group_sector.describe()

                                  momentum                                    \
                                     count      mean       std           min
sector
1차 철강 제조업                              4.0  0.143429  0.453864 -9.219858e-02
건물 건설업                                 1.0 -0.086306       NaN -8.630610e-02
기초 화학물질 제조업                            3.0  0.071607  0.222890 -1.034483e-01
기타 금융업                                 5.0 -0.008275  0.069780 -8.742004e-02
기타 전문 도매업                              1.0  0.015400       NaN  1.540041e-02
기타 화학제품 제조업                            1.0  0.013413       NaN  1.341282e-02
담배 제조업                                 1.0  0.017073       NaN  1.707317e-02
무기 및 총포탄 제조업                           1.0  1.010349       NaN  1.010349e+00
반도체 제조업                                2.0  0.379937  0.247594  2.048611e-01
보험업                                    1.0  0.250000       NaN  2.500000e-01
봉제의복 제조업                               3.0  0.224242  0.271641  2.597403e-03
부동산 임대 및 공급업                           3.0  0.041081  0.045578 -7.771561e-16
산업용 기계 및 장비 임대업                        1.0  0.104575       NaN  1.045752e-01
상품 종합 도매업                              3.0  0.154832  0.219272 -7.898260e-02
상품 중개업                                 2.0  0.249394  0.219858  9.393064e-02
석유 정제품 제조업                             1.0  0.157068       NaN  1.570681e-01
알코올음료 제조업                              1.0  0.034314       NaN  3.431373e-02
영화, 비디오물, 방송프로그램 제작 및 배급업              1.0 -0.052823       NaN -5.282332e-02
유리 및 유리제품 제조업                          1.0 -0.065600       NaN -6.560000e-02
의약품 제조업                                1.0 -0.092523       NaN -9.252282e-02
일반 목적용 기계 제조업                          1.0 -0.023645       NaN -2.364532e-02
전기 통신업                                 2.0  0.056367  0.189233 -7.744108e-02
전기업                                    1.0  0.122261       NaN  1.222607e-01
전동기, 발전기 및 전기 변환 · 공급 · 제어 장치 제조업      1.0 -0.101633       NaN -1.016334e-01
전자부품 제조업                               1.0  0.770449       NaN  7.704485e-01
종합 소매업                                 1.0  0.091667       NaN  9.166667e-02
컴퓨터 프로그래밍, 시스템 통합 및 관리업                1.0  0.061538       NaN  6.153846e-02
텔레비전 방송업                               2.0  0.461820  0.428061  1.591356e-01
토목 건설업                                 1.0 -0.065534       NaN -6.553398e-02
플라스틱제품 제조업                             2.0  0.598521  0.884866 -2.717391e-02


                                        25%       50%       75%       max
sector
1차 철강 제조업                         -0.089767 -0.079070  0.154127  0.824053
건물 건설업                            -0.086306 -0.086306 -0.086306 -0.086306
기초 화학물질 제조업                       -0.053852 -0.004255  0.159135  0.322526
기타 금융업                            -0.058824 -0.008503  0.023385  0.089987
기타 전문 도매업                          0.015400  0.015400  0.015400  0.015400
기타 화학제품 제조업                        0.013413  0.013413  0.013413  0.013413
담배 제조업                             0.017073  0.017073  0.017073  0.017073
무기 및 총포탄 제조업                       1.010349  1.010349  1.010349  1.010349
반도체 제조업                            0.292399  0.379937  0.467474  0.555012
보험업                                0.250000  0.250000  0.250000  0.250000
봉제의복 제조업                           0.072727  0.142857  0.335065  0.527273
부동산 임대 및 공급업                       0.016566  0.033133  0.061621  0.090110
산업용 기계 및 장비 임대업                    0.104575  0.104575  0.104575  0.104575
상품 종합 도매업                          0.054312  0.187608  0.271740  0.355872
상품 중개업                             0.171662  0.249394  0.327125  0.404857
석유 정제품 제조업                         0.157068  0.157068  0.157068  0.157068
알코올음료 제조업                          0.034314  0.034314  0.034314  0.034314
영화, 비디오물, 방송프로그램 제작 및 배급업         -0.052823 -0.052823 -0.052823 -0.052823
유리 및 유리제품 제조업                     -0.065600 -0.065600 -0.065600 -0.065600
의약품 제조업                           -0.092523 -0.092523 -0.092523 -0.092523
일반 목적용 기계 제조업                     -0.023645 -0.023645 -0.023645 -0.023645
전기 통신업                            -0.010537  0.056367  0.123270  0.190174
전기업                                0.122261  0.122261  0.122261  0.122261
전동기, 발전기 및 전기 변환 · 공급 · 제어 장치 제조업 -0.101633 -0.101633 -0.101633 -0.101633
전자부품 제조업                           0.770449  0.770449  0.770449  0.770449
종합 소매업                             0.091667  0.091667  0.091667  0.091667
컴퓨터 프로그래밍, 시스템 통합 및 관리업            0.061538  0.061538  0.061538  0.061538
텔레비전 방송업                           0.310478  0.461820  0.613163  0.764505
토목 건설업                            -0.065534 -0.065534 -0.065534 -0.065534
플라스틱제품 제조업                         0.285673  0.598521  0.911368  1.224215

In [157]:
momentum_count = top_group_sector.count()['momentum'].sort_values(ascending=False).head(10)
momentum_count

sector
기타 금융업          5
1차 철강 제조업       4
봉제의복 제조업        3
기초 화학물질 제조업     3
상품 종합 도매업       3
부동산 임대 및 공급업    3
텔레비전 방송업        2
전기 통신업          2
상품 중개업          2
플라스틱제품 제조업      2
Name: momentum, dtype: int64

In [158]:
for i in momentum_count.index:
  s = top[top['sector'] == i]
  std = s.std()['momentum']
  mean = s.mean()['momentum']
  nor = (top_group_sector.get_group(i)['momentum'] - mean )/std

  top_group_sector.get_group(i)['momentum'] = nor
  for j in range(len(top)):
    if top['sector'].iloc[j] == s['sector'][0]:
      top['momentum'].iloc[j] = (top['momentum'].iloc[j]-mean)/std

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

In [159]:
top_g = top.groupby('sector')
top_g.describe()

                                  momentum                                    \
                                     count          mean       std       min
sector
1차 철강 제조업                              4.0  5.551115e-17  1.000000 -0.519159
건물 건설업                                 1.0 -8.630610e-02       NaN -0.086306
기초 화학물질 제조업                            3.0  3.700743e-17  1.000000 -0.785391
기타 금융업                                 5.0  4.440892e-17  1.000000 -1.134210
기타 전문 도매업                              1.0  1.540041e-02       NaN  0.015400
기타 화학제품 제조업                            1.0  1.341282e-02       NaN  0.013413
담배 제조업                                 1.0  1.707317e-02       NaN  0.017073
무기 및 총포탄 제조업                           1.0  1.010349e+00       NaN  1.010349
반도체 제조업                                2.0  3.799367e-01  0.247594  0.204861
보험업                                    1.0  2.500000e-01       NaN  0.250000
봉제의복 제조업                               3.0  1.110223e-16  1.000000 -0.815949
부동산 임대 및 공급업                           3.0 -7.401487e-17  1.000000 -0.901335
산업용 기계 및 장비 임대업                        1.0  1.045752e-01       NaN  0.104575
상품 종합 도매업                              3.0  0.000000e+00  1.000000 -1.066323
상품 중개업                                 2.0  0.000000e+00  1.000000 -0.707107
석유 정제품 제조업                             1.0  1.570681e-01       NaN  0.157068
알코올음료 제조업                              1.0  3.431373e-02       NaN  0.034314
영화, 비디오물, 방송프로그램 제작 및 배급업              1.0 -5.282332e-02       NaN -0.052823
유리 및 유리제품 제조업                          1.0 -6.560000e-02       NaN -0.065600
의약품 제조업                                1.0 -9.252282e-02       NaN -0.092523
일반 목적용 기계 제조업                          1.0 -2.364532e-02       NaN -0.023645
전기 통신업                                 2.0  0.000000e+00  1.000000 -0.707107
전기업                                    1.0  1.222607e-01       NaN  0.122261
전동기, 발전기 및 전기 변환 · 공급 · 제어 장치 제조업      1.0 -1.016334e-01       NaN -0.101633
전자부품 제조업                               1.0  7.704485e-01       NaN  0.770449
종합 소매업                                 1.0  9.166667e-02       NaN  0.091667
컴퓨터 프로그래밍, 시스템 통합 및 관리업                1.0  6.153846e-02       NaN  0.061538
텔레비전 방송업                               2.0  0.000000e+00  1.000000 -0.707107
토목 건설업                                 1.0 -6.553398e-02       NaN -0.065534
플라스틱제품 제조업                             2.0 -5.551115e-17  1.000000 -0.707107


                                        25%       50%       75%       max
sector
1차 철강 제조업                         -0.513802 -0.490232  0.023570  1.499623
건물 건설업                            -0.086306 -0.086306 -0.086306 -0.086306
기초 화학물질 제조업                       -0.562876 -0.340360  0.392696  1.125751
기타 금융업                            -0.724400 -0.003275  0.453714  1.408171
기타 전문 도매업                          0.015400  0.015400  0.015400  0.015400
기타 화학제품 제조업                        0.013413  0.013413  0.013413  0.013413
담배 제조업                             0.017073  0.017073  0.017073  0.017073
무기 및 총포탄 제조업                       1.010349  1.010349  1.010349  1.010349
반도체 제조업                            0.292399  0.379937  0.467474  0.555012
보험업                                0.250000  0.250000  0.250000  0.250000
봉제의복 제조업                          -0.557778 -0.299606  0.407974  1.115555
부동산 임대 및 공급업                      -0.537862 -0.174389  0.450668  1.075725
산업용 기계 및 장비 임대업                    0.104575  0.104575  0.104575  0.104575
상품 종합 도매업                         -0.458425  0.149473  0.533161  0.916850
상품 중개업                            -0.353553  0.000000  0.353553  0.707107
석유 정제품 제조업                         0.157068  0.157068  0.157068  0.157068
알코올음료 제조업                          0.034314  0.034314  0.034314  0.034314
영화, 비디오물, 방송프로그램 제작 및 배급업         -0.052823 -0.052823 -0.052823 -0.052823
유리 및 유리제품 제조업                     -0.065600 -0.065600 -0.065600 -0.065600
의약품 제조업                           -0.092523 -0.092523 -0.092523 -0.092523
일반 목적용 기계 제조업                     -0.023645 -0.023645 -0.023645 -0.023645
전기 통신업                            -0.353553  0.000000  0.353553  0.707107
전기업                                0.122261  0.122261  0.122261  0.122261
전동기, 발전기 및 전기 변환 · 공급 · 제어 장치 제조업 -0.101633 -0.101633 -0.101633 -0.101633
전자부품 제조업                           0.770449  0.770449  0.770449  0.770449
종합 소매업                             0.091667  0.091667  0.091667  0.091667
컴퓨터 프로그래밍, 시스템 통합 및 관리업            0.061538  0.061538  0.061538  0.061538
텔레비전 방송업                          -0.353553  0.000000  0.353553  0.707107
토목 건설업                            -0.065534 -0.065534 -0.065534 -0.065534
플라스틱제품 제조업                        -0.353553  0.000000  0.353553  0.707107